### ISSUE TITLE
请教一下如果想要使用ricmp协议应该怎么写命令行？

### ISSUE THREAD

**Issue by egg1234** [esrrhs/spp-shadowsocks-plugin#2]
以非Android平台的命令行为例：

\# ./shadowsocks2-linux -c 'ss://AEAD_CHACHA20_POLY1305:your-password@127.0.0.1:8488' -verbose --plugin spp-shadowsocks-plugin --plugin-opts "proto=rudp" -socks :1080 

\# ./shadowsocks2-linux -s 'ss://AEAD_CHACHA20_POLY1305:your-password@:8488' -verbose --plugin spp-shadowsocks-plugin --plugin-opts "type=server;proto=rudp"

上面这两行如果想使用ricmp协议的话应该怎么写呢？

谢谢！

**Comment by esrrhs** [comment]
rudp换成ricmp即可

**Comment by esrrhs** [comment]
嗯，试试看
