### ISSUE TITLE
请教关于端口转发的问题

### ISSUE THREAD

**Issue by egg1234** [esrrhs/spp-shadowsocks-plugin#5]
vps服务器命令行
./go-shadowsocks2 -s 'ss://AEAD_CHACHA20_POLY1305:your-password@:12345' -verbose --plugin spp-shadowsocks-plugin --plugin-opts "type=server;proto=kcp"

局域网linux客户机端口转发命令行
./go-shadowsocks2 -c 'ss://AEAD_CHACHA20_POLY1305:your-password@1.2.3.4:12345' -verbose --plugin spp-shadowsocks-plugin --plugin-opts "proto=kcp" -u -udptun 0.0.0.0:2408=engage.cloudflareclient.com:2408

然后在局域网的其他机器用warp客户端如nekoray连接这台客户机的2408端口，发现连接没有反应，而且在这台客户机的控制台没有看到任何传入连接的回显日志

但同样是这台vps使用xray的服务端及xray的客户机进行端口转发，局域网的其他机器是可以用warp客户端连通到warp服务器的

请教一下是配置命令参数问题还是spp-shadowsocks-plugin方式不支持udp的端口转发？

**Comment by esrrhs** [comment]
[go-shadowsocks2](https://github.com/shadowsocks/go-shadowsocks2)不支持udp转发吧

**Comment by esrrhs** [comment]
那应该是支持的，估计是使用姿势的问题。试试去掉插件可以吗？

**Comment by esrrhs** [comment]
嗯那破案了
